// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbxqnxcuizupuvescmia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNieHFueGN1aXp1cHV2ZXNjbWlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MTc4ODksImV4cCI6MjA3NjA5Mzg4OX0.jyZ00h6qbtM3gxAFhYPVE9fTnilAOtTz_vXvhRNhPfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});